const STORICO_BUDGET_IMPORT = [
 {
  "numero": "23004",
  "fase": "AS BUILT APT",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 417.0,
  "km": 30.0,
  "speseVive": 121.0,
  "stampe": 0,
  "fileOrigine": "23004_BUDGET CONTRACT AS BUILT APT.xlsx"
 },
 {
  "numero": "23004",
  "fase": "ESECUTIVO GENERALE",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 2724.8,
  "km": 62.0,
  "speseVive": 6.0,
  "stampe": 0,
  "fileOrigine": "23004_BUDGET CONTRACT ESECUTIVO GENERALE.xlsx"
 },
 {
  "numero": "23027",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 98.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23027_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23040",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 112.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23040_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23041",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 61.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23041_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23042",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 20.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23042_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23045",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 2.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23045_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23050",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 37.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23050_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23055",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 6.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23055_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23060",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 25.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23060_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23062",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 21.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23062_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23064",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 27.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23064_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23067",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 23.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23067_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23079",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 7.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23079_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23082",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 43.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23082_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23094",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 47.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23094_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23095",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 12.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23095_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23098",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 54.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23098_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23104",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 14.5,
  "km": 40.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23104_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23106",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 144.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23106_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23114",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 147.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23114_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23115",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 21.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23115_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23118",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 28.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23118_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23119",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 21.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23119_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23120",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 26.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23120_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23121",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 15.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23121_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "23123",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 45.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "23123_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24002",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 181.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24002_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24004",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 24.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24004_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24015",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 11.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24015_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24017",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 28.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24017_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24020",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 7.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24020_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24022",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 2.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24022_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24031",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 114.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24031_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24032",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 19.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24032_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24033",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 83.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24033_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24034",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 343.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24034_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24035",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 23.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24035_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24037",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 4.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24037_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24039",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 2.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24039_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24041",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 6.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24041_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24050",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 50.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24050_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24052",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 154.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24052_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24053",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 14.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24053_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24058",
  "fase": "DM+DEF+ESEC",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 890.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24058_BUDGET CONTRACT DM+DEF+ESEC.xlsx"
 },
 {
  "numero": "24058",
  "fase": "VARIANTE OTT 2025",
  "oreSeniorEle": 6.0,
  "oreSeniorMec": 5.5,
  "oreJuniorEle": 147.0,
  "oreJuniorMec": 7.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24058_BUDGET CONTRACT VARIANTE OTT 2025.xlsx"
 },
 {
  "numero": "24060",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 97.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24060_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24067",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 46.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24067_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24071",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 18.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24071_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24072",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 16.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24072_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24076",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 3.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24076_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24078",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 68.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24078_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24079",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 2.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24079_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24081",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 40.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24081_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24084",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 1.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24084_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24085",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 40.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24085_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24086",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 102.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24086_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24088",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 7.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24088_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24090",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 82.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24090_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24091",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 1.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24091_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24092",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 14.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24092_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24093",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 3.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24093_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24094",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 63.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24094_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24095",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 2.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24095_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24096",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 30.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24096_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24097",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 43.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24097_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24098",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 1.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24098_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24099",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 132.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24099_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24100",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 112.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24100_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24101",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 59.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24101_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24105",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 37.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24105_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "24106",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 84.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "24106_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25002",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 23.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25002_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25006",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 35.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25006_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25009",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 25.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25009_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25010",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 4.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25010_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25011",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 1.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25011_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25012",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 30.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25012_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25016",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 1.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25016_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25017",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 4.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25017_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25018",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 19.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25018_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25023",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 197.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25023_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25024",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 54.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25024_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25026",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 1.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25026_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25027",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 3.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25027_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25028",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 5.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25028_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25030",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 5.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25030_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25033",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 51.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25033_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25036",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 9.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25036_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25037",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 3.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25037_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25038",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 91.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25038_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25039",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 8.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25039_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25043",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 6.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25043_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25045",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 1.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25045_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25046",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 40.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25046_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25049",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25049_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25051",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25051_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25052",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 88.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25052_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25053",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 20.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25053_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25054",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 19.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25054_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25055",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 21.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25055_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25056",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 51.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25056_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25057",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 76.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25057_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25058",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 2.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25058_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25059",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 108.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25059_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25061",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 4.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25061_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25062",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 1.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25062_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25063",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 8.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25063_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25065",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 11.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25065_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25066",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 33.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25066_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25067",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 16.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25067_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25069",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25069_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25071",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 55.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25071_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25072",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 110.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25072_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25073",
  "fase": "",
  "oreSeniorEle": 9.5,
  "oreSeniorMec": 17.5,
  "oreJuniorEle": 28.0,
  "oreJuniorMec": 56.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25073_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25074",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 2.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25074_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25075",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 10.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25075_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25076",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 6.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25076_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25077",
  "fase": "",
  "oreSeniorEle": 7.0,
  "oreSeniorMec": 11.0,
  "oreJuniorEle": 36.0,
  "oreJuniorMec": 59.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25077_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25078",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 2.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25078_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25080",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 6.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25080_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25081",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.5,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25081_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25082",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 1.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25082_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25084",
  "fase": "DEFINITIVO",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 8.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25084_BUDGET CONTRACT DEFINITIVO.xlsx"
 },
 {
  "numero": "25084",
  "fase": "VARIANTE",
  "oreSeniorEle": 4.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 4.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25084_BUDGET CONTRACT VARIANTE.xlsx"
 },
 {
  "numero": "25085",
  "fase": "",
  "oreSeniorEle": 4.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 4.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25085_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25086",
  "fase": "ESECUTIVO",
  "oreSeniorEle": 8.5,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 35.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25086_BUDGET CONTRACT ESECUTIVO.xlsx"
 },
 {
  "numero": "25086",
  "fase": "PRELIMINARE",
  "oreSeniorEle": 1.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 13.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 6.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25086_BUDGET CONTRACT PRELIMINARE.xlsx"
 },
 {
  "numero": "25088",
  "fase": "",
  "oreSeniorEle": 10.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 1.3,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25088_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25089",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 7.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25089_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25090",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 4.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 34.5,
  "oreNonClassificate": 0.0,
  "km": 3.0,
  "speseVive": 3.0,
  "stampe": 0,
  "fileOrigine": "25090_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25091",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25091_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25092",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 1.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25092_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25093",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 6.5,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 48.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25093_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25094",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 1.5,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 7.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25094_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25095",
  "fase": "",
  "oreSeniorEle": 7.0,
  "oreSeniorMec": 2.0,
  "oreJuniorEle": 81.0,
  "oreJuniorMec": 30.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25095_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25096",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 2.5,
  "oreJuniorEle": 2.5,
  "oreJuniorMec": 26.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25096_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25097",
  "fase": "",
  "oreSeniorEle": 0.5,
  "oreSeniorMec": 1.5,
  "oreJuniorEle": 6.5,
  "oreJuniorMec": 12.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25097_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25098",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 1.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 7.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25098_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25099",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 1.5,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 9.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25099_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25101",
  "fase": "",
  "oreSeniorEle": 3.5,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 9.5,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 40.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25101_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25102",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 12.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 6.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25102_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25103",
  "fase": "",
  "oreSeniorEle": 7.5,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 11.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25103_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25104",
  "fase": "",
  "oreSeniorEle": 10.5,
  "oreSeniorMec": 1.5,
  "oreJuniorEle": 18.5,
  "oreJuniorMec": 3.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25104_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25105",
  "fase": "",
  "oreSeniorEle": 4.5,
  "oreSeniorMec": 1.0,
  "oreJuniorEle": 7.0,
  "oreJuniorMec": 8.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25105_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25106",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 2.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25106_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25107",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 1.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25107_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25108",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25108_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25109",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 1.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25109_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25110",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 3.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25110_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25111",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.5,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 11.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25111_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25112",
  "fase": "",
  "oreSeniorEle": 22.0,
  "oreSeniorMec": 12.0,
  "oreJuniorEle": 25.5,
  "oreJuniorMec": 16.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25112_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25113",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 6.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25113_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "25114",
  "fase": "",
  "oreSeniorEle": 8.0,
  "oreSeniorMec": 21.5,
  "oreJuniorEle": 83.0,
  "oreJuniorMec": 179.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "25114_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26001",
  "fase": "",
  "oreSeniorEle": 5.5,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 21.5,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26001_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26002",
  "fase": "",
  "oreSeniorEle": 4.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 17.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26002_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26003",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 1.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 3.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26003_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26004",
  "fase": "",
  "oreSeniorEle": 1.0,
  "oreSeniorMec": 1.0,
  "oreJuniorEle": 7.0,
  "oreJuniorMec": 18.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26004_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26005",
  "fase": "",
  "oreSeniorEle": 20.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 25.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26005_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26007",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 390.0,
  "km": 6736.0,
  "speseVive": 694.1,
  "stampe": 0,
  "fileOrigine": "26007_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26010",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 1.5,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26010_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26011",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 4.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 6.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26011_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26012",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.5,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26012_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26013",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 2.0,
  "oreJuniorMec": 16.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26013_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26014",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 6.5,
  "oreJuniorMec": 20.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26014_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26015",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 2.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26015_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26016",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 4.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26016_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26017",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 1.5,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 4.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26017_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26018",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 5.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26018_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26019",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 5.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 63.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26019_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26020",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 2.5,
  "oreJuniorEle": 9.0,
  "oreJuniorMec": 40.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26020_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26021",
  "fase": "",
  "oreSeniorEle": 2.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 4.5,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26021_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26022",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 2.5,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26022_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26023",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 10.5,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 73.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26023_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26024",
  "fase": "",
  "oreSeniorEle": 0.5,
  "oreSeniorMec": 11.5,
  "oreJuniorEle": 17.5,
  "oreJuniorMec": 47.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26024_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26025",
  "fase": "",
  "oreSeniorEle": 1.0,
  "oreSeniorMec": 3.0,
  "oreJuniorEle": 39.0,
  "oreJuniorMec": 15.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26025_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26026",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 1.5,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26026_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26027",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 1.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26027_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26028",
  "fase": "",
  "oreSeniorEle": 3.5,
  "oreSeniorMec": 8.5,
  "oreJuniorEle": 47.0,
  "oreJuniorMec": 69.5,
  "oreNonClassificate": 0.0,
  "km": 40.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26028_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26030",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 6.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 4.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26030_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26031",
  "fase": "",
  "oreSeniorEle": 9.0,
  "oreSeniorMec": 5.5,
  "oreJuniorEle": 89.0,
  "oreJuniorMec": 59.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26031_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26032",
  "fase": "",
  "oreSeniorEle": 0.5,
  "oreSeniorMec": 2.0,
  "oreJuniorEle": 7.5,
  "oreJuniorMec": 26.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26032_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26033",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 15.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26033_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26034",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 1.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26034_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26035",
  "fase": "",
  "oreSeniorEle": 4.0,
  "oreSeniorMec": 1.5,
  "oreJuniorEle": 27.5,
  "oreJuniorMec": 58.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26035_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26036",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 2.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26036_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26037",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 4.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26037_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26038",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 7.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 1.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26038_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26039",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 2.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26039_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26040",
  "fase": "",
  "oreSeniorEle": 2.5,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 3.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26040_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26041",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 4.0,
  "oreJuniorEle": 3.5,
  "oreJuniorMec": 7.5,
  "oreNonClassificate": 0.0,
  "km": 3.0,
  "speseVive": 3.0,
  "stampe": 0,
  "fileOrigine": "26041_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26042",
  "fase": "",
  "oreSeniorEle": 1.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 4.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26042_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26043",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 2.0,
  "oreJuniorEle": 2.0,
  "oreJuniorMec": 16.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26043_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26044",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 5.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26044_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26045",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 2.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 27.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26045_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26046",
  "fase": "",
  "oreSeniorEle": 2.0,
  "oreSeniorMec": 3.0,
  "oreJuniorEle": 8.0,
  "oreJuniorMec": 9.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26046_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26047",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 4.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26047_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26049",
  "fase": "",
  "oreSeniorEle": 0.5,
  "oreSeniorMec": 9.0,
  "oreJuniorEle": 8.0,
  "oreJuniorMec": 38.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26049_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26050",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 2.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 5.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26050_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26051",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 1.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26051_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26052",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 1.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26052_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26053",
  "fase": "",
  "oreSeniorEle": 5.5,
  "oreSeniorMec": 8.5,
  "oreJuniorEle": 18.5,
  "oreJuniorMec": 44.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26053_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26054",
  "fase": "",
  "oreSeniorEle": 3.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 5.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26054_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26055",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 3.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26055_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26056",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 1.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 4.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26056_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26057",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 7.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26057_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26058",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 3.5,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26058_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26059",
  "fase": "",
  "oreSeniorEle": 0.5,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 7.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26059_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26060",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.5,
  "oreJuniorEle": 2.0,
  "oreJuniorMec": 9.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26060_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26061",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 4.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26061_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26062",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.5,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 12.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26062_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26063",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 1.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26063_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26064",
  "fase": "",
  "oreSeniorEle": 0.5,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 4.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26064_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26066",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 4.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26066_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26067",
  "fase": "",
  "oreSeniorEle": 10.5,
  "oreSeniorMec": 7.0,
  "oreJuniorEle": 52.5,
  "oreJuniorMec": 81.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26067_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26068",
  "fase": "",
  "oreSeniorEle": 4.5,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 37.5,
  "oreJuniorMec": 49.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26068_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26069",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 1.0,
  "oreJuniorMec": 11.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26069_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26070",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 3.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 2.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26070_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26071",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 11.5,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26071_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26073",
  "fase": "",
  "oreSeniorEle": 8.5,
  "oreSeniorMec": 4.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26073_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26074",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 5.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26074_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26075",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 1.5,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 9.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26075_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26076",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 7.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 14.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26076_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26077",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 1.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 2.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26077_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26078",
  "fase": "",
  "oreSeniorEle": 2.5,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26078_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26079",
  "fase": "",
  "oreSeniorEle": 0.0,
  "oreSeniorMec": 1.5,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26079_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26081",
  "fase": "",
  "oreSeniorEle": 4.0,
  "oreSeniorMec": 0.5,
  "oreJuniorEle": 1.5,
  "oreJuniorMec": 3.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26081_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26082",
  "fase": "",
  "oreSeniorEle": 22.0,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 0.0,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26082_BUDGET CONTRACT.xlsx"
 },
 {
  "numero": "26083",
  "fase": "",
  "oreSeniorEle": 1.5,
  "oreSeniorMec": 0.0,
  "oreJuniorEle": 19.5,
  "oreJuniorMec": 0.0,
  "oreNonClassificate": 0.0,
  "km": 0.0,
  "speseVive": 0.0,
  "stampe": 0,
  "fileOrigine": "26083_BUDGET CONTRACT.xlsx"
 }
];
